version: '3'

services:
  pinterest_clone:
    environment:
      GIN_MODE: debug
      APP_URL: http://localhost
      APP_PORT: 3000
      PGDATABASE: pc
      PGHOST: db
      PGUSER: postgres
      PGSSLMODE: disable
	  # GH_CLIENT_ID: foo
	  # GH_CLIENT_SECRET: bar
    build: .
    command: tail -f /dev/null
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - .:/go/src/github.com/ravster/pinterest_clone

  db:
    image: postgres:9.6.9-alpine
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
